### ISSUE TITLE
Upvotes are shown as downvotes on profile

### ISSUE THREAD

**Issue by rberends** [Erudika/scoold#338] opened 2022-09-01 06:59 UTC
Hey there,

A small bug we've noticed. It seems that on people's profile pages, the upvote count they have done is shown as the downvote count.

Here's a profile with 15 upvotes made according to the database:

```json
{"updated":1661955214213,"name":"xxxx","votes":0,"version":0,"stored":true,"indexed":true,"cached":true,"identifier":"ldap:xxxx","active":true,"twoFA":false,"email":"xxxx@xxxx.com","picture":"https://www.gravatar.com/avatar?d=mm&size=400"}
{"updated":1662009370191,"name":"xxxx","tags":["flow-maestro"],"votes":135,"version":0,"stored":true,"indexed":true,"cached":true,"properties":{"lastseen":1661957560596,"favorites":["1471151835350831104","1471077007210057728","1447496936075563008"],"originalPicture":"https://www.gravatar.com/avatar?d=mm&size=400","favtags":[],"favspaces":[],"darkmodeEnabled":false,"upvotes":15,"bannedUntil":0,"favtagsString":"","customBadges":[{"name":"Flow Maestro","icon":"","description":"Heeft xxxx gestart!","style":"background-color: #f57913; color: #ffffff;","tag":"flow-maestro"}],"yearlyVotes":135,"commentEmailsEnabled":false,"originalName":"xxxx","totalVotes":15,"quarterlyVotes":135,"replyEmailsEnabled":false,"monthlyVotes":10,"anonymityEnabled":false,"website":"","comments":0,"groups":"admins","downvotes":0,"picture":"http://xxxx/upload/files/profile_1462369625864933376_hix_rgb_beeldmerk.18b82f7dd01f%20%281%29.png","aboutme":"","favtagsEmailsEnabled":false,"badges":",editor,eureka,eureka,eureka,eureka,eureka,eureka,eureka,eureka,eureka,eureka,eureka,noob,eureka,eureka,enthusiast,","badgesMap":{"editor":1,"enthusiast":1,"eureka":13,"noob":1},"spaces":["scooldspace:zorgportaal:Zorgportaal","scooldspace:xxxx:xxxx"],"weeklyVotes":68,"location":"","complete":false,"status":""}}
```
And here's how it is displayed:

![image](https://user-images.githubusercontent.com/59354731/187851689-d7c16c1c-6b0e-44dd-9f0c-92c912ca2c0e.png)

I have not been able to find out exactly where in the code this flippening takes place.

**Comment by albogdano** [comment] 2022-09-02 11:13
Thanks Roel, this bug has already been fixed. Expect a new release soon. 
Duplicate of #324

**Closed by albogdano** 2022-09-02 11:13 UTC
