### ISSUE TITLE
Image upload does not work consistently

### ISSUE THREAD

**Issue by svengrabic** [Erudika/scoold#209] opened 2020-12-06 22:49 UTC
Version used: Pro

Browsers: Safari 13.1.1 (15609.2.9.1.2), Firefox

Steps to reproduce: Add answer to existing question -> try to insert image ("Insert image" button) -> Save

Behaviour: "Save" button hit is ignored, no changes on the site (no redirect or reload), image is not inserted. Sometimes, after few tryouts and page reload, image just appears within the answer. 

Notice: This behaviour is not present all the time, there are cases when it just works as expected. Unfortunately, couldn't find any pattern which should isolate unexpected behaviour case.

**Comment by albogdano** [comment] 2020-12-07 08:22
I think this was fixed in the last version. What version are you on?

**Comment by svengrabic** [comment] 2020-12-07 09:07
Scoold Pro
Scoold version: 1.40.3
Production mode: true

**Comment by albogdano** [comment] 2020-12-07 19:47
I couldn't reproduce it. Do you see any errors in the browser dev console?

**Comment by svengrabic** [comment] 2020-12-08 10:07
Please try following:

1) add some answer in existing topic
2) Edit answer -> go on "Attach files" button and choose image from disc
3) Save -> for me this time it really saved and image was there
4) edit the answer again and delete the image reference
5) Save -> nothing happens (like button does not have any action attached to it) -> no dev console output
6) on page refresh editing is saved and image is really deleted

**Comment by albogdano** [comment] 2020-12-09 10:01
Yes, indeed this was fixed in 1.40.3.

**Closed by albogdano** 2020-12-09 10:01 UTC
Labels: bug
