### ISSUE TITLE
Authentication failed (Scoold with Docker)

### ISSUE THREAD

**Issue by flavienbwk** [Erudika/scoold#197] opened 2020-09-10 12:55 UTC
Hi,

I am trying to get started with Scooled but I can't manage to login, always getting : `Authentication failed or was canceled.`

My configuration : 

```
### Minimal configuration ###
# the name of the application
para.app_name = "Scoold"
# the port for Scoold
para.port = 8000
# change this to "production" later
para.env = "development"
# the public-facing URL where Scoold is hosted
para.host_url = "http://localhost:8000"
# the URL of Para - can also be "https://paraio.com"
para.endpoint = "http://para:8080"
# access key for your Para app
para.access_key = "app:scoold"
# secret key for your Para app
para.secret_key = "change_to_long_random_string"
para.app_secret_key = "change_to_long_random_string"
# the email or identifier of the admin user - check Para user object
para.admins = "admin@domain.com"
##############################

####### Authentication #######
para.security.allow_unverified_emails = true
# enable or disable email and password authentication
para.password_auth_enabled = true
# Session cookie name
para.auth_cookie = "scoold-auth"
# Facebook - create your own Facebook app first!
para.fb_app_id = ""
# Google - create your own Google app first!
para.google_client_id = ""
###############################

### Misc. ###
# if false, commenting is allowed after 100+ reputation
para.new_users_can_comment = true
# if true, posts by new users require approval from moderator
para.posts_need_approval = false
# reputation needed for posts to be auto-approved
para.posts_rep_threshold = 100
# needed for geolocation filtering of posts
para.gmaps_api_key = ""
# Enable/disable near me feature (geolocation)
para.nearme_feature_enabled = false
# GA code
para.google_analytics_id = ""
# enables syntax highlighting in posts
para.code_highlighting_enabled = true
# If true, the default space will be accessible by everyone
para.is_default_space_public = true
# If true, users can change their profile pictures
para.avatar_edits_enabled = true
# If true, users can change their names
para.name_edits_enabled = true
# Enable/disable webhooks support
para.webhooks_enabled = true
# Enable/disable wiki style answers
para.wiki_answers_enabled = true
# Comment limits
para.max_comments_per_id = 1000
para.max_comment_length = 1024
# Post body limit (characters)
para.max_post_length = 20000
# Tags per post limit, must be < 100
para.max_tags_per_post = 20
# Sets the default tag for new questions
para.default_question_tag = "" # "question"
# Enable/disable numeric pagination (< 1 2 3...N >)
para.numeric_pagination_enabled = false
# Selects the default language to load on startup, defaults to 'en'
para.default_language_code = ""

# styling
para.inline_css = ".navbar-color { color: #292929; }"
```

My compose file (Dockerfiles are the same than the official ones) : 

```
version: '3.2'

services:
   para:
     build:
      context: .
      dockerfile: para.Dockerfile
     image: erudikaltd/para
     ports:
       - "8080:8080"
     volumes:
       - type: volume
         source: paraData
         target: /para/data
       - type: volume
         source: paraLib
         target: /para/lib
       - type: bind
         source: ./para-application.conf
         target: /para/application.conf
     restart: always
     env_file: para.env

   scoold:
     depends_on:
       - para
     build:
      context: .
      dockerfile: Dockerfile
     image: erudikaltd/scoold
     ports:
       - "8000:8000"
     volumes:
       - type: bind
         source: ./scoold-application.conf
         target: /scoold/application.conf
     restart: always
     env_file: scoold.env

volumes:
  paraData:
  paraLib:
```

Thank you for your help !

**Comment by albogdano** [comment] 2020-09-10 17:05
How exactly do you try to log in? The configuration looks good but you should also check the logs for any errors.

**Comment by flavienbwk** [comment] 2020-09-10 17:10
Thanks for your reply. First I've signed up with `admin@domain.com`. Then I tried to login in `http://localhost:8000/signin` with `admin@domain.com` and it shows me that error.

Container logs don't show anything apart from the **first** login try, getting : `400 - User belongs to an app that does not exist.`

**Comment by albogdano** [comment] 2020-09-10 17:15
You may have skipped a few steps there:
- is Para initialized? if not open localhost:8080/v1/_setup
- have you created the app `app:scoold` in Para by using the access keys for the root app `app:para`?

**Comment by flavienbwk** [comment] 2020-09-10 17:26
Wow yeah indeed. Setup is not very convinient. And I don't really see how to do it in Docker as the `para-cli` commands creates a `config.json` file where you run it.

**Comment by flavienbwk** [comment] 2020-09-10 17:57
OK I think I've managed to initialize correctly my instance following the [`quick start guide`](https://github.com/Erudika/scoold#quick-start-with-a-self-hosted-para-backend-harder). I've previously removed my volumes so it's a raw install.

Now it says the email is already taken. What is the default password for admin authentication ?

**Comment by albogdano** [comment] 2020-09-10 18:12
The Para CLI tool should work with docker out of the box. Is there a problem with that? `para-cli new-app "scoold" --name "Scoold"` is correct.
There is no default password - you should login with the password you used when you registered the admin@domain.com acoount.

**Comment by flavienbwk** [comment] 2020-09-10 18:25
I understood the problem the my admin user not wanting to log in : I think this is a bug (from my point of view).

It has to do with cookies : my cookies were not removed among my multiple reinstall trials !

**Comment by albogdano** [comment] 2020-09-11 06:58
Is there anything else blocking you from logging in? If the issue is resolved we can close this.

**Comment by flavienbwk** [comment] 2020-09-11 09:05
If we don't consider the cookie problem, this issue is solved.

**Closed** 2020-09-11 09:09 UTC
