### ISSUE TITLE
Problem logging in with Microsoft

### ISSUE THREAD

**Issue by Teg79** [Erudika/scoold#2] opened 2017-05-11 08:02 UTC
Hi,
I set up Scoold on my local box, para is running on the same machine and I want to use the Microsoft login.

I created a new application on my Microsoft page and put the app id and the secret on the application.conf, when I try to login with Microsoft it redirects me to the MS login page, but the final redirect goes in error:

AADSTS50011: The reply address 'http://localhost:8080/microsoft_auth' does not match the reply addresses configured for the application

In my application on MS I set the redirect url to http://localhost:8000/microsoft_auth, I dont know why it uses the port 8080 for the redirect.

The attached conf file has been renamed because github wants .txt

[application.conf.txt](https://github.com/Erudika/scoold/files/992251/application.conf.txt)

**Comment by albogdano** [comment] 2017-05-11 10:21
@Teg79  What's your initial URL - the one you redirect your users to? In particular, the `redirect_uri` parameter is crucial here. Also, how are you setting the port to be 8000? `server.port = 8000`?

**Comment by Teg79** [comment] 2017-05-11 11:01
@albogdano the url is localhost:8000, the port is set by the command line as per your example:
`java -jar -Dserver.port=8000 -Dconfig.file=./application.conf scoold-1.24.7.jar`

**Comment by albogdano** [comment] 2017-05-11 11:07
Ok, I must have missed to add a check for `server.port` in the code (only checks `para.port` atm). I must have been sleepy... Try it again but replace `-Dserver.port` with `-Dpara.port` and see what happens. I will fix it in the meantime.

**Comment by Teg79** [comment] 2017-05-11 11:14
Changed the command to `java -jar -Dpara.port=8000 -Dconfig.file=./application.conf scoold-1.24.7.jar` but MS always tries the url `http://localhost:8080/microsoft_auth`

**Comment by albogdano** [comment] 2017-05-11 11:20
I assume that's because your `para.endpoint` is set to `http://localhost:8080`.

**Comment by Teg79** [comment] 2017-05-11 11:23
If I put `para.endpoint = "http://localhost:8080"` i get:
`2017-05-11 13:21:47 [INFO ] Initialized ParaClient with endpoint http://localhost:8000 and access key 'app:para'.

2017-05-11 13:21:47 [DEBUG] PUT /v1/_settings, entity: Entity{entity={gh_app_id=, gh_secret=, in_app_id=, in_secret=, tw_secret=, tw_app_id=, ms_secret=*************ZjB, ms_app_id=*********a0855, signin_failure=http://localhost:8000/signin?code=3&error=true, signin_success=http://localhost:8000/signin/success?jwt=?}, variant=Variant[mediaType=application/json, language=null, encoding=null], annotations=[]}

2017-05-11 13:21:48 [ERROR] No connection to Para backend.
`

So it cannot connect to the para server

**Comment by albogdano** [comment] 2017-05-11 11:33
Are you sure you are running Para on localhost? `curl http://localhost:8080/v1` should return a JSON object?

**Comment by Teg79** [comment] 2017-05-11 11:44
Yes, the JSon is:
`{
  "info" : "Para - a backend for busy developers.",
  "version" : "1.24.2"
}`

But where is possible to set ip and port for the para server?

**Comment by albogdano** [comment] 2017-05-11 11:51
Para has the same config variable for port `para.port` or `server.port`. What I'm saying is that your client is set to connect to `localhost:8000` which is wrong. `para.endpoint` and your `ParaClient` endpoints must match and point to a Para instance.

**Comment by Teg79** [comment] 2017-05-11 12:16
I've both applications (para and scoold) in the same folder with the application.conf attached on the first post, this can be a problem?

**Comment by Teg79** [comment] 2017-05-11 12:25
Not the scoold application.conf contains `para.endpoint = "http://localhost:8080"` like before andit starts again.

MS is looking for `http://localhost:8080/microsoft_auth` as redirect_uri but it hangs waiting for a response

**Comment by albogdano** [comment] 2017-05-11 12:25
Oh, don't do this. Keep the configuration files separate.

**Comment by Teg79** [comment] 2017-05-11 12:30
Now the scoold application.conf contains para.endpoint = "http://localhost:8080" like before andit starts again.

Para is in another folder now

MS is looking for http://localhost:8080/microsoft_auth as redirect_uri but it hangs waiting for a response.
Is http://localhost:8080/microsoft_auth correct? Para is listening on that port

The Para log contains many rows like:
`2017-05-11 14:29:19 [WARN ] [para-es-1] high disk watermark [90%] exceeded on [nlglin7xRN2jYie1U2pjYg][para-es-1][/Users/Teg/Dev/Scoold/Para/data/para-dev/nodes/0] free: 11gb[4.7%], shards will be relocated away from this node

2017-05-11 14:29:19 [INFO ] [para-es-1] rerouting shards: [high disk watermark exceeded on one or more nodes]
`

**Comment by Teg79** [comment] 2017-05-11 12:37
A little step forward, the hang was a proxy problem.

Now it redirects correctly to para redirect uri `http://localhost:8080/microsoft_auth` and then it redirects to `http://localhost:8080/signin` but I get only a white page.

I think the last redirect must be to `http://localhost:8000/signin` where the scoold is listening

**Comment by albogdano** [comment] 2017-05-11 12:45
Yes, `http://localhost:8080/microsoft_auth` is the correct `redirect_uri`. This is where you need to set your `signin_success` and `signin_failure` urls. But Scoold automatically sets these on startup.

**Comment by Teg79** [comment] 2017-05-11 12:48
Yes, this works, but after the `http://localhost:8080/microsoft_auth` it redirects on `http://localhost:8080/signin` where it opens a white page.

**Comment by albogdano** [comment] 2017-05-11 12:53
You can try setting `para.security.signin_success = "http://localhost:8000/signin?jwt=?"` in your Para config file.

**Comment by Teg79** [comment] 2017-05-11 13:10
In the Scoold log:
2017-05-11 14:55:54 [DEBUG] PUT /v1/_settings, entity: Entity{entity={gh_app_id=, gh_secret=, in_app_id=, in_secret=, tw_secret=, tw_app_id=, ms_secret=************ZjB, ms_app_id=3f*************0855, signin_failure=http://localhost:8000/signin?code=3&error=true, signin_success=http://localhost:8000/signin/success?jwt=?}, variant=Variant[mediaType=application/json, language=null, encoding=null], annotations=[]}

It looks ok: `signin_success=http://localhost:8000/signin/success?jwt=?`

I put the `para.security.signin_success = "http://localhost:8000/signin?jwt=?"` in the application.conf in the Para folder and relaunched it with `java -Dconfig.file=./application.conf -jar para-1.24.2.war` but it always redirects to `http://localhost:8080/signin`

**Comment by albogdano** [comment] 2017-05-11 13:33
So it must be an error, also try setting `para.security.signin_failure = "http://localhost:8000/signin?error=true&code=3"` in Para config.

**Comment by albogdano** [comment] 2017-05-11 13:51
@Teg79 I'll be releasing a new patched version of both Scoold and Para later today. For the time being only Facebook and Google work for Scoold.

**Comment by Teg79** [comment] 2017-05-11 13:51
Ok, now I get to the Scoold app! The login is failed but on MS the login was successfull

**Comment by albogdano** [comment] 2017-05-11 13:52
Yea, I know theres's a bug in Para.

**Comment by Teg79** [comment] 2017-05-11 13:54
Please put also an option to disable facebook login

**Comment by albogdano** [comment] 2017-05-11 13:54
:+1: will do

**Comment by albogdano** [comment] 2017-05-12 22:51
This is now fixed in Para v1.24.3, I've just released Scoold 1.24.8, please update.

**Closed by albogdano** 2017-05-12 22:51 UTC

**Comment by Teg79** [comment] 2017-05-15 07:10
I updated Para and Scoold versions, but the problem is the same, failed login using different valid MS accounts

**Comment by albogdano** [comment] 2017-05-15 08:32
Check your configuration, the issue is most likely there.

**Comment by Teg79** [comment] 2017-05-15 14:55
Ok, after moving Para to another folder I didnt moved his "data", now the login is working
Thank you!

**Comment by albogdano** [comment] 2017-05-15 17:55
No worries, if you need more assistance, feel free to contact me, here or on Gitter chat.

**Comment by bviktor** [comment] 2019-02-14 16:28
@Teg79 could you please explain your final Para & Scoold configuration?

Also, how did you create the app in Azure? I'm trying to allow our Office 365 users to log in. MS auth sounds great because it should fetch the avatars automatically.

What kind of app did you create? Native or web? Also, what permissions did you add? I've set `read full profile for all users` I think. The more detailed, the merrier :D I'm having the mentioned white screen with

```
http://localhost:8080/signin?code=3&error=true
```

too, and not sure how to proceed.

**Comment by albogdano** [comment] 2019-02-14 19:33
@bviktor Microsoft apparently have migrated the management of OAuth apps to Azure. The steps are the following:
1. Create a new app on Azure or https://apps.dev.microsoft.com
2. Create a new "Client secret" 
![image](https://user-images.githubusercontent.com/346873/52812148-802ee100-309f-11e9-853b-96a9f9b84385.png)
3. Whitelist the redirect URIs 
![image](https://user-images.githubusercontent.com/346873/52812293-cd12b780-309f-11e9-8a77-eb8829e46aa8.png)
4. Permissions should be set automatically by the client through the requested scope but here's mine:
![image](https://user-images.githubusercontent.com/346873/52812367-f6cbde80-309f-11e9-9d67-665e6faf3fa4.png)
5. Configure Scoold to use the client secret above - set `para.ms_app_id` and `para.ms_secret`

**Comment by bviktor** [comment] 2019-02-15 13:52
Thanks, I created a new app, now not directly from the Azure Portal, but from https://apps.dev.microsoft.com instead. Set the app ID and secret in Scoold's config as

```
para.ms_app_id = "***"
para.ms_secret = "***"
```

I also set the redirect URIs. The good news is that it's at least different now, it goes to

http://localhost:8080/signin/success?jwt=(very long token here)

But that's it. It's still a white page. I tried in a different browser, disabling adblocker, etc, no change.

I also tried setting

```
para.security.signin_success = "http://localhost:8000/signin?jwt=?"
```

in Para's config, same result. Then also tried setting "Home page" to http://localhost:8000/ on apps.dev.microsoft.com, no change...

The para and scoold consoles don't show anything related.

This is the sign-in log in azure portal, those interruptions look weird:

![image](https://user-images.githubusercontent.com/5798552/52860827-e283f200-3130-11e9-8d08-c60e0373c909.png)

If I click on one, it says:

- Sign-in error code: 50058
- Failure reason: The application tried to perform a silent sign in and the user could not be silently signed in. The application needs to start an interactive flow giving users an option to sign in. Contact app owner.

or 

- Sign-in error code: 50140
- Failure reason: This error occurred due to 'Keep me signed in' interrupt when the user was signing-in.

After this, if I open a new tab with localhost:8000 in the same private session, it won't load the page anymore, just "Waiting for localhost...". If I close the private session and re-open localhost:8000, it shows the log-in page immediately again. Until I log in again, at which point it does the same. Redirect to 8080's white page, and no response on 8000.

**Comment by bviktor** [comment] 2019-02-15 13:56
Wait a minute, I think I got it:

```
para.host_url = "http://localhost:8000/"
```

Although at first it showed the login screen as if I wasn't signed in, but when I clicked manually on questions, it showed my avatar on the top right and all was good. Will play around some more.

**Comment by albogdano** [comment] 2019-02-15 16:45
@bviktor There is indeed a small bug with avatars not showing up on return from Microsoft login page. I'll look into it. `para.security.signin_success` is set automatically so you can remove it from the config file.

**Comment by bviktor** [comment] 2019-02-15 17:11
Nah, I think there's more to it, it's not just the avatar. It shows the sign in button too (instead of an avatar or grey rectangle). There's a 401 and an "unknown domain" message in the console, too.

Additionally, Azure seems to behave totally randomly, sometimes the app works, sometimes it won't, even though I create them the same way...

Will play around this more next week.

**Comment by albogdano** [comment] 2019-02-15 23:39
@bviktor Try to pull from master - I've fixed the issue where users appear unauthenticated right after they return from the identity provider. It was due to `SameSite=Strict` which is now `=Lax`.

**Comment by bviktor** [comment] 2019-02-16 01:13
Thanks, but may I ask, why does the client (browser) have to talk to the backend directly in the first place? This will beg for apocalypse when I try putting this all behind Nginx with SSL and various security headers. Besides having to turn of all kinds of security measures (like the one you committed), it's a layer violation, it exposes the backend's API to the public, and I'll also have to use 2 hostnames just so the client can reach both the front- and backend on the normal https port, then hop around them just for logging in. I don't quite understand the principle.

**Comment by albogdano** [comment] 2019-02-16 12:53
@bviktor Para is the backend and it handles all authentication requests. The API is protected. Scoold should work fine behind a proxy. The principle is to completely decouple the backend (server) from the application (client), thereby allowing you to have multiple client applications connected to the server. Separation of concerns, basically.
